version: 2
updates:
    # Backend
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: friday
  - package-ecosystem: "npm"
    # Frontend
    directory: "/app"
    schedule:
      interval: "weekly"
      day: friday