@server=http://localhost:8080/api
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTA3MDA2MzQsImlhdCI6MTcxMDY5ODgzNCwibmJmIjoxNzEwNjk4ODM0LCJyb2xlIjoiYWRtaW4iLCJzdWIiOiIyOTA2ZTc0OC0xZGMxLTQxMjktOGEzMC1iZTlmNzc5Nzk0MmQifQ.ew4AWD4bhsv3tA9Yc91sak09SXBLVKUkGJblup-62cg
### Test connection
GET {{server}}/health

### Test PG connection
GET {{server}}/health/pg

###! ADMIN
### Get all active users
GET {{server}}/admin/users
Authorization: Bearer {{token}}
### Get all active habits
GET {{server}}/admin/habits
Authorization: Bearer {{token}}
### Get all habit records
GET {{server}}/admin/records
Authorization: Bearer {{token}}


### Create new user
POST {{server}}/auth/register
content-type: application/json

{
    "email": "admin@email.com",
    "password": "admin"
}

### Login user
POST {{server}}/auth/login
content-type: application/json

{
    "email": "admin@email.com",
    "password": "admin"
}

### Logout user
GET  {{server}}/auth/logout
content-type: application/json
Authorization: Bearer {{token}}


### Patch user
PATCH  {{server}}/users/a646fe3e-8421-4bd6-bd96-c3f42d2ac32f
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "Maciej"
}

### Get active user by ID with all habits and records
GET {{server}}/users/5d0c7168-5741-4fd4-8cd6-0f5d2fa14ab1
Authorization: Bearer {{token}}

### Delete active user by ID
DELETE  {{server}}/users/a123e4567-e89b-12d3-a456-426655440000
Authorization: Bearer {{token}}

### Create new habit
POST {{server}}/habits
content-type: application/json
Authorization: Bearer {{token}}

{
    "userID": "5d0c7168-5741-4fd4-8cd6-0f5d2fa14ab1",
    "name": "Test habit John",
    "description" : "A new test habit for John",
    "target" : 2
}

### Patch habit
PATCH  {{server}}/habits/05dcb7fe-fdd5-4745-ba3b-f7069c2fa1bd
content-type: application/json
Authorization: Bearer {{token}}

{
    "name": "Unhealthy lunch"
}

### Delete active habit by ID
DELETE  {{server}}/habits/eba507df-1d7f-4e55-b5e0-20152e9f7442
Authorization: Bearer {{token}}

### Create new habit record
POST {{server}}/records
content-type: application/json
Authorization: Bearer {{token}}

{
    "habitID": "57dbdb0a-9fee-45c2-a677-daacfd6431b1"
}

### Delete active habit record by ID
DELETE  {{server}}/records/e3037fb1-2c88-4fad-8dea-4e10cfb2d0ae
Authorization: Bearer {{token}}